#!/bin/bash

# Function to install packages if not already installed
install_package() {
    if ! command -v "$1" &>/dev/null; then
        echo "Installing package: $1"
        sudo apt-get update -y -qq && \
        sudo apt-get install -y "$1" -qq || {
            echo "Failed to install package: $1"
            exit 1
        }
    else
        echo "$1 is already installed."
    fi
}

# Install Nginx
echo "Installing Nginx..."
install_package nginx

# Configure Nginx
echo "Configuring Nginx..."

# Define server configuration
server_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}"

# Backup default server config file
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.backup

# Apply server configuration
echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default >/dev/null

# Restart Nginx
echo "Restarting Nginx..."
sudo service nginx restart

echo "Nginx configured successfully with custom header X-Served-By."

